services:
  - type: web
    runtime: python
    name: payroll-portal
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"

      - key: FLASK_DEBUG
        value: "0"

      - key: PYTHONDONTWRITEBYTECODE
        value: "1"

      - key: DATABASE_URL
        fromDatabase:
          name: payroll-db
          property: connectionString

    autoDeploy: true

databases:
  - name: payroll-db
    plan: free
    postgresMajorVersion: 15
