services:
  - type: web
    name: payroll-portal
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: FLASK_DEBUG
        value: "0"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    databases:
      - name: payroll_bf35
        plan: free
        postgresMajorVersion: "15"
    autoDeploy: true
